name: 'postio2015'
version: 0.0.1
description: Post I/O Tour presentation
author: Valentyn Shybanov <olostan@gmail.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dacsslide: 'any'
  angular: '>=1.0.0 <1.3.0'
  csslib_transform: '>=0.0.1 <0.1.0'
  pretty_samples: 'any'
transformers:
- angular
- dacsslide
- csslib_transform